import { hex, bgHex, cols } from '../../cols/colorPack';

export default {
	name: 'github',
	styles: {
		'.hljs': [hex('#c9d1d9'), bgHex('#0d1117')],
		'.hljs-doctag': [hex('#ff7b72')],
		'.hljs-keyword': [hex('#ff7b72')],
		'.hljs-meta .hljs-keyword': [hex('#ff7b72')],
		'.hljs-template-tag': [hex('#ff7b72')],
		'.hljs-template-variable': [hex('#ff7b72')],
		'.hljs-type': [hex('#ff7b72')],
		'.hljs-variable.language_': [hex('#ff7b72')],
		'.hljs-title': [hex('#d2a8ff')],
		'.hljs-title.class_': [hex('#d2a8ff')],
		'.hljs-title.class_.inherited__': [hex('#d2a8ff')],
		'.hljs-title.function_': [hex('#d2a8ff')],
		'.hljs-attr': [hex('#79c0ff')],
		'.hljs-attribute': [hex('#79c0ff')],
		'.hljs-literal': [hex('#79c0ff')],
		'.hljs-meta': [hex('#79c0ff')],
		'.hljs-number': [hex('#79c0ff')],
		'.hljs-operator': [hex('#79c0ff')],
		'.hljs-variable': [hex('#79c0ff')],
		'.hljs-selector-attr': [hex('#79c0ff')],
		'.hljs-selector-class': [hex('#79c0ff')],
		'.hljs-selector-id': [hex('#79c0ff')],
		'.hljs-regexp': [hex('#a5d6ff')],
		'.hljs-string': [hex('#a5d6ff')],
		'.hljs-meta .hljs-string': [hex('#a5d6ff')],
		'.hljs-built_in': [hex('#ffa657')],
		'.hljs-symbol': [hex('#ffa657')],
		'.hljs-comment': [hex('#8b949e')],
		'.hljs-code': [hex('#8b949e')],
		'.hljs-formula': [hex('#8b949e')],
		'.hljs-name': [hex('#7ee787')],
		'.hljs-quote': [hex('#7ee787')],
		'.hljs-selector-tag': [hex('#7ee787')],
		'.hljs-selector-pseudo': [hex('#7ee787')],
		'.hljs-subst': [hex('#c9d1d9')],
		'.hljs-section': [hex('#1f6feb'), cols.bold],
		'.hljs-bullet': [hex('#f2cc60')],
		'.hljs-emphasis': [hex('#c9d1d9'), cols.italic],
		'.hljs-strong': [hex('#c9d1d9'), cols.bold],
		'.hljs-addition': [hex('#aff5b4'), bgHex('#033a16')],
		'.hljs-deletion': [hex('#ffdcd7'), bgHex('#67060c')],
	},
};
