import { hex, bgHex, cols } from '../../cols/colorPack';

export default {
	name: 'monokai',
	styles: {
		'.hljs': [bgHex('#272822'), hex('#ddd')],
		'.hljs-tag': [hex('#f92672')],
		'.hljs-keyword': [hex('#f92672'), cols.bold],
		'.hljs-selector-tag': [hex('#f92672'), cols.bold],
		'.hljs-literal': [hex('#f92672'), cols.bold],
		'.hljs-strong': [hex('#f92672')],
		'.hljs-number': [hex('#f92672')],
		'.hljs-name': [hex('#f92672')],
		'.hljs-code': [hex('#66d9ef')],
		'.hljs-attribute': [hex('#bf79db')],
		'.hljs-attr': [hex('#bf79db')],
		'.hljs-symbol': [hex('#bf79db')],
		'.hljs-regexp': [hex('#bf79db')],
		'.hljs-link': [hex('#bf79db')],
		'.hljs-string': [hex('#a6e22e')],
		'.hljs-bullet': [hex('#a6e22e')],
		'.hljs-subst': [hex('#a6e22e')],
		'.hljs-title': [hex('#a6e22e'), cols.bold],
		'.hljs-section': [hex('#a6e22e'), cols.bold],
		'.hljs-emphasis': [hex('#a6e22e')],
		'.hljs-type': [hex('#a6e22e'), cols.bold],
		'.hljs-built_in': [hex('#a6e22e')],
		'.hljs-selector-attr': [hex('#a6e22e')],
		'.hljs-selector-pseudo': [hex('#a6e22e')],
		'.hljs-addition': [hex('#a6e22e')],
		'.hljs-variable': [hex('#a6e22e')],
		'.hljs-template-tag': [hex('#a6e22e')],
		'.hljs-template-variable': [hex('#a6e22e')],
		'.hljs-title.class_': [hex('#ffffff')],
		'.hljs-class .hljs-title': [hex('#ffffff')],
		'.hljs-comment': [hex('#75715e')],
		'.hljs-quote': [hex('#75715e')],
		'.hljs-deletion': [hex('#75715e')],
		'.hljs-meta': [hex('#75715e')],
		'.hljs-doctag': [hex('#75715e'), cols.bold],
		'.hljs-selector-id': [cols.bold],
	},
};
