import { hex, bgHex, cols } from '../../cols/colorPack';

export default {
	name: 'vs',
	styles: {
		'.hljs': [hex('#000'), bgHex('#fff')],
		'.hljs-comment': [hex('#008000')],
		'.hljs-quote': [hex('#008000')],
		'.hljs-variable': [hex('#008000')],
		'.hljs-keyword': [hex('#00f')],
		'.hljs-selector-tag': [hex('#00f')],
		'.hljs-built_in': [hex('#00f')],
		'.hljs-name': [hex('#00f')],
		'.hljs-tag': [hex('#00f')],
		'.hljs-string': [hex('#a31515')],
		'.hljs-title': [hex('#a31515')],
		'.hljs-section': [hex('#a31515')],
		'.hljs-attribute': [hex('#a31515')],
		'.hljs-literal': [hex('#a31515')],
		'.hljs-template-tag': [hex('#a31515')],
		'.hljs-template-variable': [hex('#a31515')],
		'.hljs-type': [hex('#a31515')],
		'.hljs-addition': [hex('#a31515')],
		'.hljs-deletion': [hex('#2b91af')],
		'.hljs-selector-attr': [hex('#2b91af')],
		'.hljs-selector-pseudo': [hex('#2b91af')],
		'.hljs-meta': [hex('#2b91af')],
		'.hljs-doctag': [hex('#808080')],
		'.hljs-attr': [hex('#f00')],
		'.hljs-symbol': [hex('#00b0e8')],
		'.hljs-bullet': [hex('#00b0e8')],
		'.hljs-link': [hex('#00b0e8')],
		'.hljs-emphasis': [cols.italic],
		'.hljs-strong': [cols.bold],
	},
};
